# Generated by Django 3.1 on 2020-08-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_created_at'),
        ('users', '0002_auto_20200822_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughMadeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('made_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.maderecipe')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('made_recipe', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='maderecipe',
            name='recipes',
            field=models.ManyToManyField(through='users.ThroughMadeRecipe', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='maderecipe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='made_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
